// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOWHsPPXodq5EuhaEXSfoLw9vfGYGTjj8',
    appId: '1:1091785317203:web:0560ec13f743516f649fa6',
    messagingSenderId: '1091785317203',
    projectId: 'sheru-2eb0f',
    authDomain: 'sheru-2eb0f.firebaseapp.com',
    storageBucket: 'sheru-2eb0f.appspot.com',
    measurementId: 'G-BSWZH3HRMY',
  );

  static const String webClientId =
      '1:1091785317203:web:0560ec13f743516f649fa6.apps.googleusercontent.com';

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdliZ_GAfcFAjalNUKtw_xIt4LJc_jVSw',
    appId: '1:1091785317203:android:8903f5a04aebcb58649fa6',
    messagingSenderId: '1091785317203',
    projectId: 'sheru-2eb0f',
    storageBucket: 'sheru-2eb0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6y_UARU2Ay5r98hzO9t6zgmom5e6qHz0',
    appId: '1:1091785317203:ios:b515ff9fbd49ed18649fa6',
    messagingSenderId: '1091785317203',
    projectId: 'sheru-2eb0f',
    storageBucket: 'sheru-2eb0f.appspot.com',
    iosBundleId: 'com.example.getFlutterFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6y_UARU2Ay5r98hzO9t6zgmom5e6qHz0',
    appId: '1:1091785317203:ios:b515ff9fbd49ed18649fa6',
    messagingSenderId: '1091785317203',
    projectId: 'sheru-2eb0f',
    storageBucket: 'sheru-2eb0f.appspot.com',
    iosBundleId: 'com.example.getFlutterFire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOWHsPPXodq5EuhaEXSfoLw9vfGYGTjj8',
    appId: '1:1091785317203:web:ce06fb955769a92b649fa6',
    messagingSenderId: '1091785317203',
    projectId: 'sheru-2eb0f',
    authDomain: 'sheru-2eb0f.firebaseapp.com',
    storageBucket: 'sheru-2eb0f.appspot.com',
    measurementId: 'G-XJLR16BX85',
  );
}
